#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh &

#bspc monitor -d I II III IV V VI VII VIII IX
bspc monitor -d        

bspc config border_width         2
bspc config window_gap         	12 

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox -o desktop=^2 state=fullscreen
bspc rule -a TelegramDesktop -o desktop=^5 state=fullscreen
bspc rule -a mpv state=floating
bspc rule -a Guvcview -o desktop=^4
bspc rule -a guvcview state=floating rectangle=320x240+1600+840 sticky=on layer=above
bspc rule -a code-oss state=fullscreen -o desktop=^3

alacritty 2>/dev/null &
telegram-desktop 2>/dev/null &
firefox
